// Generated by CoffeeScript 1.11.1
var dialogPurchaseVoucher, dialogPurchaseVoucherPurchasePressed, dialogValidateVoucher, dialogValidateVoucherValidatePressed, retrieveVouchers;

dialogValidateVoucher = function() {
  var el;
  el = document.getElementById('dialogValidateVoucher');
  el.style.visibility = el.style.visibility === 'visible' ? 'hidden' : 'visible';
};

dialogPurchaseVoucher = function() {
  var el;
  el = document.getElementById('dialogPurchaseVoucher');
  return el.style.visibility = el.style.visibility === 'visible' ? 'hidden' : 'visible';
};

dialogPurchaseVoucherPurchasePressed = function(e) {
  var apiUrl, data, email, json, numberOfVouchers, targetHost, valuePerVoucher;
  valuePerVoucher = parseInt(jQuery('#inputPurchaseVoucherType option:selected').text());
  numberOfVouchers = parseInt(jQuery('#inputPurchaseVoucherCount').val());
  email = jQuery('#inputPurchaseVoucherEmail').val();
  if (!(valuePerVoucher > 0)) {
    return alert('Invalid voucher amount');
  }
  if (!(numberOfVouchers > 0)) {
    return alert('Invalid voucher count');
  }
  if (numberOfVouchers > 100) {
    return alert('Can only print less than 100 vouchers at once');
  }
  data = {
    valuePerVoucher: valuePerVoucher,
    numberOfVouchers: numberOfVouchers,
    email: email
  };
  json = JSON.stringify(data);
  if (window.location.hostname === 'localhost') {
    targetHost = 'http://localhost:8671';
  } else {
    targetHost = 'https://bdemr.services';
  }
  apiUrl = targetHost + '/api/1/' + 'bdemr-com-voucher-purchase';
  return jQuery.ajax({
    url: apiUrl,
    data: json,
    method: 'POST',
    dataType: 'json',
    success: function(response, textStatus, jqXHR) {
      var redirectionUrl;
      if (response.hasError) {
        return alert(response.error.message);
      } else {
        redirectionUrl = response.data.redirectionUrl;
        if (redirectionUrl) {
          return window.location = redirectionUrl;
        } else {
          return alert('Server Error. Expected redirectionUrl');
        }
      }
    },
    error: function(jqXHR, textStatus, errorThrown) {
      console.log(jqXHR, textStatus, errorThrown);
      return alert(textStatus + errorThrown);
    }
  });
};

dialogValidateVoucherValidatePressed = function(e) {
  var apiUrl, data, json, targetHost, voucherCode;
  voucherCode = jQuery('#inputValidateVoucherCode').val();
  if (!(voucherCode.length > 10)) {
    return alert('Invalid voucher code');
  }
  data = {
    voucherCode: voucherCode
  };
  json = JSON.stringify(data);
  if (window.location.hostname === 'localhost') {
    targetHost = 'http://localhost:8671';
  } else {
    targetHost = 'https://bdemr.services';
  }
  apiUrl = targetHost + '/api/1/' + 'bdemr-com-voucher-validate';
  return jQuery.ajax({
    url: apiUrl,
    data: json,
    method: 'POST',
    dataType: 'json',
    success: function(response, textStatus, jqXHR) {
      if (response.hasError) {
        return alert(response.error.message);
      } else {
        return alert(response.data.message);
      }
    },
    error: function(jqXHR, textStatus, errorThrown) {
      console.log(jqXHR, textStatus, errorThrown);
      return alert(textStatus + errorThrown);
    }
  });
};

jQuery(document).on('ready', function(e) {
  jQuery('#dialogPurchaseVoucherPurchaseButton').click(dialogPurchaseVoucherPurchasePressed);
  jQuery('#dialogValidateVoucherValidateButton').click(dialogValidateVoucherValidatePressed);
  if (getQueryVariable('op') === 'retrieve-voucher') {
    return retrieveVouchers();
  }
});


  function getQueryVariable(variable) {
    var query = window.location.search.substring(1);
    var vars = query.split("&");
    for (var i=0;i<vars.length;i++) {
      var pair = vars[i].split("=");
      if (pair[0] == variable) {
        return pair[1];
      }
    }
    return null
  }
;

retrieveVouchers = function() {
  var apiUrl, data, json, publicToken, targetHost;
  publicToken = getQueryVariable('public-token');
  if (!publicToken) {
    alert('Missing public token');
  }
  data = {
    publicToken: publicToken
  };
  json = JSON.stringify(data);
  if (window.location.hostname === 'localhost') {
    targetHost = 'http://localhost:8671';
  } else {
    targetHost = 'https://bdemr.services';
  }
  apiUrl = targetHost + '/api/1/' + 'bdemr-com-voucher-retrieve';
  return jQuery.ajax({
    url: apiUrl,
    data: json,
    method: 'POST',
    dataType: 'json',
    success: function(response, textStatus, jqXHR) {
      var message, voucherList;
      if (response.hasError) {
        return alert(response.error.message);
      } else {
        if ('status' in response.data && response.data.status === 'success') {
          voucherList = response.data.voucherList;
          message = 'Your ordered vouchers are: ' + (voucherList.join(', '));
          return alert(message);
        } else {
          return alert('Unknown server side error');
        }
      }
    },
    error: function(jqXHR, textStatus, errorThrown) {
      console.log(jqXHR, textStatus, errorThrown);
      return alert(textStatus + errorThrown);
    }
  });
};
